### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 0leks** [strikerz76/Paint#1]
- [ ] save previous settings (brush size, color pallet) per file/folder for convenience
- [x] improve brush size selection
- [ ] add settings menu for visual stuff like tiling and background color
- [ ] add tooltips with name and hotkey and remove button names
- [ ] don't allow zooming while selecting to avoid breaking selection
- [x] rebrand to KPaint
![UI-idea](https://user-images.githubusercontent.com/1296131/106209059-4286ce00-6179-11eb-9b7b-98a9970bc971.png)
